package com.example.adminpanel_1.api.catalogExport

import android.os.Parcelable
import kotlinx.android.parcel.Parcelize

@Parcelize
data class Product(
//    val accessories: List<Accessory>,
//    val adult: String,
//    val alt_parent: List<AltParent>,
    val article: String,
    val article_for_display: String,
   // val brand: Brand,
   // val characteristics: Characteristics,
//    val color: Color,
//    val condition: Condition,
//    val countdown_description: CountdownDescription,
    val countdown_end_time: String,
    val creation_time: String,
    val currency: Currency,
    val description: Description,
    val discount: Int,
    val display_in_showcase: Int,
    //val export_to_marketplace: List<ExportToMarketplace>,
    val gallery_360: List<String>,
    val gallery_common: List<String>,
    //val gifts: List<Gift>,
    val gtin: String,
    val guarantee_length: String,
//    val guarantee_shop: GuaranteeShop,
//    val h1_title: H1Title,
//    val icons: List<Icon>,
    val images: List<String>,
    //val installments_payment: InstallmentsPayment,
    val isExportPriceLevelsAllowed: Boolean,
    val link: String,
    //val marketplace_description: MarketplaceDescription,
    val minimal_order: String,
    val mod_title: ModTitle,
    val mpn: String,
    val multiplicity: String,
    //val parent: Parent,
    val parent_article: String,
    val popularity: Int,
    val presence: Presence,
    val price: Double,
    //val price_levels: List<PriceLevel>,
    val price_old: Double,
    val quantity: Int,
//    val razmer: Razmer,
//    val rozetka_title: RozetkaTitle,
//    val seo_description: SeoDescription,
//    val seo_keywords: SeoKeywords,
//    val seo_title: SeoTitle,
//    val short_description: ShortDescription,
//    val shtrixKod: ShtrixKod,
//    val slug: String,
//    val special_delivery_terms: SpecialDeliveryTerms,
    val title: Title,
//    val volume: Volume,
//    val wholesale_price_3: String,
//    val xarakteristikaVSistemnomShablone: XarakteristikaVSistemnomShablone
) :Parcelable